### ISSUE TITLE
Warning: failed to open read

### ISSUE THREAD

**Issue by Salvobioinfo** [skovaka/uncalled4#6] opened 2024-03-21 08:54 UTC
Hi,
I'm running uncalled4 with direct RNA data. 
The cmd i'm using is: 
`uncalled4 align RNA.fasta /path_Dir/pod5/ --bam-in Sorted.bam -p 5 --flowcell FLO-MIN106 --kit SQK-RNA002 --eventalign-out -x summary_pod5.tsv --eventalign-flags “samples”
` 
I get the following error: 
`Loading read index 'summary_pod5.tsv'
Auto-detected flowcell='FLO-MIN106' kit='SQK-RNA002'
Warning: failed to open read 72c798b5-52e5-45b8-a55d-57575c10c724 ('72c798b5-52e5-45b8-a55d-57575c10c724')
Warning: failed to open read ab141b09-4879-42b4-bdb3-6f071aea9454 ('ab141b09-4879-42b4-bdb3-6f071aea9454')
`
I’m not able to figure out why it happens.
Thanks in advance !

PS if it can be useful. 
I converted fast5 to pod5 using the python package [POD5](https://pypi.org/project/pod5/) and created the summary with the same tool.

**Comment by skovaka** [comment] 2024-03-21 18:00
I just pushed an update which will output a slightly more detailed error message, so try re-running with that. 

Do any reads successfully align, and are those reads listed in "summary_pod5.tsv"? If you have any subdirectories in your pod5 paths make sure to include the `-r` option.

You could also try running without the `-x summary_pod5.tsv` and uncalled4 should generate its own index at `/path_Dir/pod5/read_index.txt`. That may take a few minutes or more to run depending on how many files you have, but it may help narrow down the problem

**Comment by skovaka** [comment] 2024-03-25 17:40
It looks like the issue was likely caused by "split reads" which were recently introduced in Dorado (https://github.com/skovaka/uncalled4/pull/8). This should now be fixed in the latest commit.

**Comment by Salvobioinfo** [comment] 2024-03-25 17:46
Hi, I’ve tested it out. 
Now it works !!!
Concerning the error messages.
The summary is missing the listed reads mentioned in the error messages. I looked for those reads also in the basecalled fastq file, but didn’t find any positive results. I suspect there’s something related to the dodado basecaller.

Since i add in my command line --eventalign-flags “samples, read_name”, but i dind’t get the read_name in the output, i have one further question.  

Does the “read_index” column in the output correspond to the line number in the index file created by the tool?

**Comment by skovaka** [comment] 2024-03-25 17:58
To get read names and sample coordinates in eventalign use `--eventalign-flags samples,print-read-names`, **not** "read_name"

Without that flag, read_index should correspond to the line number in the input BAM file, excluding the header and unmapped reads and starting at 0. That allows for proper handling of multimapped reads, while the read_index would be ambiguous

**Comment by Han-ju** [comment] 2024-03-29 05:05
Hi, if you still have same problem and expected split reads, please confirm applying `samtools fastq -T "mv,ts,pi,sp,ns" <file>.bam > file.fastq` rather than `"mv,ts"` at fastq extraction step. The code of loading split reads requires `pi`, `sp` and `ns` tags, which is not written at latest `README.md`.

**Comment by skovaka** [comment] 2024-03-29 13:26
Thanks, just updated the README to include those tags

**Closed by skovaka** 2024-03-29 13:26 UTC
