### ISSUE TITLE
Seg fault in align

### ISSUE THREAD

**Issue by cnk113** [skovaka/uncalled4#4] opened 2024-03-15 19:34 UTC
Hi,

I'm running Uncalled4 with direct RNA data from dorado basecalled and aligned reads.
Command:
```
uncalled4 align --bam-in filtered.bam --rna -o uc4.bam ../../ref.fasta fast5_pass
```
However I get a seg fault (near the end?) of the alignment:
```
Using model `rna_r9.4.1_70bps_5mer`
Warning: failed to open read d6f....
Segmentation fault (core dumped)
```
I removed the read name for brevity, I assume it's due to the missing read; would there be a possibility to just skip missing reads?

Thanks,
Chang

**Comment by skovaka** [comment] 2024-03-18 13:20
You're right, it looks like because of the missing read, which should not result in a segmentation fault. I just added a check for that and pushed it, it should now just output the warning and continue

**Comment by skovaka** [comment] 2024-03-18 18:19
Sorry for the issues! Are any alignments successfully output? And did you basecall with the `--emit-moves` option? That option should add "mv:" and "ts:" tags to the BAM file. If those tags are missing from any reads it could cause a problem, although it should just print a warning and not segfault.

Also, was your data sequenced with RNA002 or RNA004? We currently only support RNA002, but hoping to add 004 support soon. You could try removing the `--rna` flag since Uncalled4 can auto-detect the chemistry in most cases. The `--rna` flag is mainly for use with a custom pore model, and it shouldn't cause any issues but it's worth trying to remove it.

**Comment by skovaka** [comment] 2024-03-19 13:40
The read_index should be built automatically, what is the error you're getting? If you don't have write permission to your FAST5 directory then that could cause an error, which I could add a workaround for. You could also input a "sequencing_summary.txt" to the "--read-index" flag which can serve as a read index.

In your initial attempt, does it fail after aligning some reads, or do all reads fail? If all reads fail, is it possible for you to share a small example FAST5 and BAM file for me to test? Otherwise, could you just send me the BAM entry for the read which is failing? Sorry again for the trouble

**Comment by skovaka** [comment] 2024-03-20 19:55
You can change the port via the `--port` option. To access remotely I generally use SSH port forwarding, for example to connect local port 8000 to remote port 8000: `ssh -NL 8000:localhost:8000 <username>@<server.edu>`

**Comment by skovaka** [comment] 2024-03-20 19:56
And I should be able take a look at your test dataset later this week! Thank you for sharing

**Comment by skovaka** [comment] 2024-03-21 18:05
Could you also share the reference FASTA corresponding to your test dataset? I couldn't find anything suspicious from what you gave me, but can't run uncalled4 without the reference. I did notice that in your original post you said the warning was `failed to open read d6f....`, but there is no read starting with "`d6f`" in your test dataset. If you could share your exact error output for that test dataset that would be helpful

I also just pushed an update which will output a slightly more detailed error message for the "failed to open read" issue, which could help narrow it down. I also included a trackplot and dotplot example, along with bug fixes to those commands

**Comment by skovaka** [comment] 2024-03-25 17:38
Thanks again for sharing. It turns out the skipped reads and the segmentation fault are two separate errors:

The skipped reads were because I had not considered "split reads" recently introduced in Dorado, now helpfully fixed by @Han-ju https://github.com/skovaka/uncalled4/pull/8

The segfault appears to be caused by a bug in the latest version of Dorado (https://github.com/nanoporetech/dorado/issues/635). I just added an error check and a workaround in the latest commit. Now it will print warnings instead of crashing, and you can add the `--zero-ts` flag to correct the offending tag. It looks like an easy to fix issue for Dorado, so hopefully that flag will be unnecessary in future releases

**Closed as completed** 2024-03-27 16:38 UTC
